name: Ruff Linting

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Run Linter
        run:  |
          set -x
          pip install -e .[dev]
          ruff format --check .
          ruff check .
