name: build wheels

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'john-science/mazelib'

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Update package index
        run: sudo apt-get update
      - name: Install PIP Packages
        run: |
          pip install -U pip
          pip install -e .
      - name: Build Wheels
        run: |
          set -x
          pip install -U wheel
          mkdir dist
          pip wheel . -w dist/
          rm -f dist/Cython*.whl
          rm -f dist/numpy*.whl
      - name: Archive PIP wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mazelib-wheels
          path: |
            dist/mazelib*.whl
          retention-days: 5
